Geometry to lat lon
InsightLab/PyMove pull request #139
Opened 2020-10-14 23:06 UTC by MCavalcante16

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] I have read the **CONTRIBUTING** document.
-   [x] My code follows the code style of this project (see `.code-style.md`).
-   [x] All new and existing tests passed (see `.testing.md`).
-   [x] I have added tests to cover my changes.
-   [x] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly (see `.documentation.md`).

## Description

-   What is the new behavior (if this is a feature change)?
    A function to converts the geometry column to latitude and longitude
    columns (named 'lat' and 'lon'), removing geometries
    that are not of the Point type.

2020-10-23 21:20 UTC, flych3r requested changes

2020-10-23 21:20 UTC, flych3r commented on pymove/utils/conversions.py
> +        move_data[constants.LATITUDE] = move_data[constants.GEOMETRY].y
Dessa forma fica restringido para funcionar apenas com o geopandas.
Uma forma de fazer isso é aplicar um `map` na coluna para pegar os tipos.
```python
>>> df['geometry'].map(type)
0         <class 'shapely.geometry.point.Point'>
1         <class 'shapely.geometry.point.Point'>
2         <class 'shapely.geometry.point.Point'>
3         <class 'shapely.geometry.point.Point'>
```
Dessa forma deve comparar direto com o objeto `shapely.geometry.point.Point`, assim não precisa dessa contante.

```python
>>> df['geometry'].map(type) == shapely.geometry.Point
```

O interessante é que com o `map` é mais rápido que extraindo o `type` do `geodataframe`.

![Captura de tela de 2020-10-23 18-01-52](https://user-images.githubusercontent.com/26675637/97053831-02042c80-155a-11eb-8775-e0923ced55cf.png)


Pra extrair o `x` e `y`, pode fazer novamente com o `map`
```python
>>> df['geometry'].map(lambda p: p.x)
0         116.319236
1         116.319322
2         116.319402
3         116.319389
```

Ta recebendo o nome da coluna `geometry` mas não está usando. Mudar onde tem `constants.GEOMETRY` pelo parâmetro.

2020-10-23 21:20 UTC, flych3r commented on pymove/tests/test_utils_conversions.py
> +    new_move_df = conversions.geometry_point_to_lat_and_lon(move_df, inplace=False)
O nome da função é `geometry_points_to_lat_and_lon`.
O teste também falha porque os dataframes tem colunas diferentes.
Pode fazer assim, modificar o dataframe esperado para possuir uma coluna de `Point`.
```python
from shapely.geometry import Point

Point(116.36184, 39.77529)
```

Deve remover também esse `check_dtype=False`.

2020-10-24 16:00 UTC, MCavalcante16 commented on pymove/utils/conversions.py
> +        move_data[constants.LATITUDE] = move_data[constants.GEOMETRY].y
Massa. Nao conhecia essa função map

2020-10-25 21:38 UTC, flych3r approved these changes

2020-10-25 21:38 UTC, merged