Conversion lat and lon graus to decimal
InsightLab/PyMove pull request #153
Opened 2020-11-18 19:38 UTC by MCavalcante16

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [x] I have read the **CONTRIBUTING** document.
-   [x] My code follows the code style of this project (see `.code-style.md`).
-   [x] All new and existing tests passed (see `.testing.md`).
-   [x] I have added tests to cover my changes.
-   [x] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly (see `.documentation.md`).

## Description

-   What is the new behavior (if this is a feature change)?
    Converts latitude and longitude format from
    decimal degrees to decimal format.

2020-11-20 13:07 UTC, flych3r requested changes

2020-11-20 13:07 UTC, flych3r commented on pymove/utils/conversions.py
> +            move_data[longitude][i] = float(copy_lon[i][:-1]) * -1
Tentar vetorizar o código.

2020-12-02 14:46 UTC, flych3r requested changes

2020-12-02 14:46 UTC, flych3r commented on pymove/utils/distances.py
> +def distance_in_meters(lat1, lon1, lat2, lon2):
Melhor renomear para `euclidean_distance`

2020-12-02 14:46 UTC, flych3r commented on pymove/tests/test_utils_distances.py
> +def text_distance_in_meters():
Está escrito `text` ao invés de `test`

2020-12-03 00:44 UTC, MCavalcante16 commented on pymove/utils/distances.py
> +def distance_in_meters(lat1, lon1, lat2, lon2):
euclidean_distance_in_meters seria melhor, não? a distancia euclidiana pura não é dessa forma.

2020-12-03 01:34 UTC, flych3r requested changes

2020-12-03 01:34 UTC, flych3r commented on pymove/tests/test_utils_distances.py
> +def test_distance_in_meters():
Lembra que o teste deve ter o mesmo nome da função que está tratando, só com o prefixo `test_`

2020-12-11 22:13 UTC, flych3r approved these changes

2020-12-11 22:13 UTC, merged