Examples
InsightLab/PyMove pull request #184
Opened 2021-04-30 20:50 UTC by joaocarvoli

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] I have read the **CONTRIBUTING** document.
-   [ ] My code follows the code style of this project (see `.code-style.md`).
-   [ ] All new and existing tests passed (see `.testing.md`).
-   [ ] I have added tests to cover my changes.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly (see `.documentation.md`).

## Description

-   What is the current behavior? (You can also link to an open issue here)
    

-   What is the new behavior (if this is a feature change)?

2021-04-30 21:32 UTC, flych3r requested changes

2021-04-30 21:32 UTC, flych3r commented on pymove/utils/datetime.py
> +    >>> 2021-04-29
O nome da variável esta diferente. `dt` e `df`. Mudar pra `dt`

2021-04-30 21:32 UTC, flych3r commented on pymove/utils/datetime.py
> +    data_to_str(df)
O nome do método é `date_to_str`

2021-04-30 21:32 UTC, flych3r commented on pymove/utils/datetime.py
> +    >>> 2021-04-30 <class 'str'>
Esse exemplo não corresponde com o método.

2021-04-30 21:32 UTC, flych3r commented on pymove/utils/datetime.py
> +    import datetime
Renomear para `datetime_to_min`. Renomear também em `pymove/tests/test_utils_datetime`

2021-04-30 21:32 UTC, flych3r commented on pymove/utils/datetime.py
> +    from datetime import datetime
Não entendi os imports. Acho que não precisa.

2021-04-30 21:32 UTC, flych3r commented on pymove/utils/datetime.py
> +    - You need to use 'str_to_time' module to work with 'datetime.datetime' object
Mostrar as definições das variaveis no lugar dos prints.

2021-04-30 21:32 UTC, flych3r commented on pymove/utils/datetime.py
> +    Example:
Renomear para `datetime_to_str`. Renomear também em `pymove/tests/test_utils_datetime`

2021-04-30 22:18 UTC, joaocarvoli commented on pymove/utils/datetime.py
> +    - You need to use 'str_to_time' module to work with 'datetime.datetime' object
Somente nesses casos em que eu "mostro" o valor antes de usá-la na função?

2021-05-03 20:52 UTC, flych3r requested changes

2021-05-03 20:52 UTC, flych3r commented on pymove/tests/test_utils_datetime.py
> +def test_datetime_to_min():
A execução gera o seguinte erro:
```python
AttributeError: module 'pymove.utils.datetime' has no attribute 'to_str'
```
Atualizar também a chamada da função

2021-05-03 20:52 UTC, flych3r commented on pymove/tests/test_utils_datetime.py
> +def test_datetime_to_min():
A execução gera o seguinte erro:
```python
AttributeError: module 'pymove.utils.datetime' has no attribute 'to_min'
```
Atualizar também a chamada da função

2021-05-03 20:52 UTC, flych3r commented on pymove/utils/datetime.py
> +    start_time_2 = str_to_datetime(time_2)
Pode remover esse trecho e usar como exemplo objetos datetime, e mostrar o import do str_to_datetime.
```python
from datetime import datetime
from pymove.utils.datetime import str_to_datetime

start_time_1 = datetime.datetime(2020, 6, 29, 0, 0)
start_time_2 = str_to_datetime('2020-06-29 12:45:59')
```

2021-05-03 20:52 UTC, flych3r commented on pymove/utils/datetime.py
> +    >>>  2020-06-29 12:45:59
Similar ao comentário na função elapsed_time_dt. Adicionar tambem a definição do `time_now`

2021-05-03 20:52 UTC, flych3r commented on pymove/utils/datetime.py
> +    >>> False <class 'bool'>
Aqui não da pra saber bem o que a função faz. O que acontece é, quando passa uma data, dado um pais e um estado, vai ser verificado se aquele dia é um dia útil ou não. No exemplo pode passar uma data que sabe que no brasil não é feriado, e uma que  sabe que é pra mostrar melhor.

2021-05-03 20:52 UTC, flych3r commented on pymove/utils/datetime.py
> +    >>> 4 < class 'int' >
Assim como na working_day, aqui é melhor mostrar no exemplo uma data fixa, mostrando uma que é fim de semana e uma que não é.

2021-05-04 18:56 UTC, flych3r requested changes

2021-05-04 18:56 UTC, flych3r commented on pymove/utils/datetime.py
> +    from datetime import datetime
Não usa o ` from datetime import datetime`, pode remover.

2021-05-04 18:56 UTC, flych3r commented on pymove/utils/datetime.py
> +    from datetime import datetime
Não usa o `from datetime import datetime`, pode remover.

2021-05-04 18:56 UTC, flych3r commented on pymove/utils/datetime.py
> +    import datetime
Não usa o `import datetime`, pode remover.

2021-05-04 18:56 UTC, flych3r commented on pymove/utils/datetime.py
> +    import holidays
Pode deixar so o `from pymove.utils.datetime import str_to_datetime`

2021-05-04 18:56 UTC, flych3r commented on pymove/utils/datetime.py
> +     PREV_LOCAL, STD, SUM, TIME_TO_PREV,)
Pode remover esses imports

2021-05-04 18:56 UTC, flych3r commented on pymove/utils/datetime.py
> +    from pandas import DataFrame
Mesmas observações de `generate_time_statistics`.

2021-05-04 18:56 UTC, flych3r commented on pymove/utils/datetime.py
> +      local_label  prev_local    time_to_prev
Aqui ficaria ao contrário. Esse `>>>` significa que é a saída do comando anterior.
Pode colocar só assim:
`````python
print(df)
>>> local_label  prev_local    time_to_prev
  0   261          NaN             NaN
  1   580         261.0           252.0
  2   376         580.0           91.0
  3   386         376.0          17449.0
  4   644         386.0          21824.0
````

2021-05-04 21:16 UTC, flych3r approved these changes

2021-05-05 02:57 UTC, joaocarvoli reviewed
Ok!

2021-05-05 03:01 UTC, joaocarvoli reviewed
OK

2021-05-05 14:15 UTC, merged